repos:
  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.20.0
    hooks:
      - id: blacken-docs
        additional_dependencies:
        - black==25.9.0
        files: 'docs/.*\.txt$'
        args: ["--rst-literal-block"]

  - repo: https://github.com/PyCQA/isort
    rev: 7.0.0
    hooks:
      - id: isort
        exclude: |
          (^|/)migrations/

  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        exclude: |
          (^|/)migrations/
        args: [--max-line-length=120]

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.9.0
    hooks:
      - id: black
        args: ["--line-length=88", "--force-exclude", ".*/migrations/.*"]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.36.0
    hooks:
      - id: eslint
